[book]
authors = ["brxken128"]
language = "en"
src = "book/src"
title = "Dexios"
description = "Documentation for Dexios"

[rust]
edition = "2024"

[build]
build-dir = "target/mdbook"       # generated output stays outside tracked docs
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors
