name: Build and Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: clippy (ubuntu-latest, stable)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust toolchain with clippy
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: Clippy
      run: cargo clippy --no-deps

  check:
    name: check (ubuntu-latest, stable)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Check
      run: cargo check --release

  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build
        run: cargo build --release

      - if: matrix.os != 'windows-latest'
        name: Strip
        run: strip target/release/dexios

      - if: matrix.os == 'ubuntu-latest'
        name: Hash the Binary
        run: sha256sum target/release/dexios

      - if: matrix.os == 'ubuntu-latest'
        name: Upload Binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dexios-linux-amd64
          path: target/release/dexios
      - if: matrix.os == 'macos-latest'
        name: Upload Binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dexios-macos-amd64
          path: target/release/dexios
      - if: matrix.os == 'windows-latest'
        name: Upload Binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dexios-windows-amd64
          path: target/release/dexios.exe
