name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          - macos-latest
        rust:
          - "1.88"
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install Rust toolchain
        run: rustup toolchain install ${{ matrix.rust }} --profile minimal

      - name: Select Rust toolchain
        run: rustup default ${{ matrix.rust }}

      - name: Restore cargo cache
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('Cargo.lock') }}

      - name: Run tests
        run: cargo test --workspace --all-features --release --verbose
